language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"

before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ppa
  # - sudo apt-get update -qq
  - apt-get update || echo "ignoring rabbitmq.com apt"
  - sudo apt-get install -y libgdal1h gdal-bin libgdal-dev

install:
  - pip install -r requirements.txt
  - pip install nose
  - pip install coverage
  - pip install coveralls
  - pip install .

script:
  - nosetests --with-coverage

after_success:
  - coveralls
